# Generated by Django 4.1.5 on 2023-01-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
    ]
