# Generated by Django 4.1.4 on 2023-02-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_presentation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
